version: '3.9'

services:
  db:
    image: postgres:15.1
    container_name: cshop_db
    restart: always
    ports:
      - '32700:5432'
    env_file: .env
    volumes:
      - ./data:/var/lib/postgres/data

